netty:
  port: 8888
server:
  servlet:
    session:
      persistent: true

# spring 相关配置
spring:
  h2:
    console:
      # 是否开启 web 访问数据库（url: http://${ip}:${port}/h2-console）
      enabled: true
#
jpom:
#  subTitle: "测试"
#  name: "ccsfsdfdsf"
#  loginTitle: dsfasdf
#  logoFile: https://www.surely.cool/surely-vue-logo.png
#  disabledCaptcha: true
#  notificationPlacement: topLeft
