#运行端口号
server:
  port: 2122
  servlet:
    session:
      cookie:
        name: JPOMID-SERVER
      timeout: 1H
  compression:
    # gzip 压缩
    enabled: true
    #mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,image/png
    min-response-size: 2048
spring:
  application:
    name: jpomServer

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      # 上传文件大小限制
      max-request-size: 2GB
      max-file-size: 1GB
banner:
  msg: Jpom-Server Starting
# 静态资源配置
interceptor:
  resourceHandler: /css/**,/fonts/**,/img/**,/js/**
  resourceLocation: classpath:/dist/css/,classpath:/dist/fonts/,classpath:/dist/img/,classpath:/dist/js/
  initPackageName: io.jpom.common.interceptor
# 启动完成自动初始化指定包
preload:
  packageName: io.jpom.system.init
# 强制去掉空格
request:
  trimAll: true
  parameterXss: false
  copyInputStream: true
#在线编辑格式
#fileFormat: txt|yml|conf|properties|ini
